services:
  - type: web
    name: mass-salud
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm run migrate && npm run start'
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mas_salud
          property: connectionString
