services:
  - type: web
    name: mass-salud
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm run migrate && npm run start'
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgres://salud:FGJ20p7SeIPnf15nRXc9jO4jRwbxhMR6@dpg-cp6f906ct0pc7392ch40-a/mas_salud
